version: "3"
services:
  nodeA:
    image: redbackup/node:${TAG}
    networks:
      - redbackup
  nodeB:
    image: redbackup/node:${TAG}
    networks:
      - redbackup
  client1:
    image: redbackup/client:${TAG}
    networks:
      - redbackup
    command: nodeA
networks:
  redbackup: