version: "2"
services:
  nodeA:
    image: redbackup/node:${TAG}
    networks:
      - redbackup_minimal
  nodeB:
    image: redbackup/node:${TAG}
    networks:
      - redbackup_minimal
  client1:
    image: redbackup/client:${TAG}
    networks:
      - redbackup_minimal
    command: nodeA
networks:
  redbackup_minimal: